### ISSUE TITLE
[BUG] UTF-8

### ISSUE THREAD

**Issue by CassianoD2** [oconfronto/oconfronto#13]
Diversas páginas ainda mostrar o erro de UTF-8, ou seja, não mostra **ç,ã,á**.

![image](https://github.com/user-attachments/assets/09b54e81-ac91-4137-ba7c-5ee277128fc0)

Seria necessário investigar a possibilidade de adicionar o campo header no HTML setando para UTF-8.

**Comment by Diguzz** [comment]
Na real já foi feito isso. Ainda temos que investigar mais a fundo a real solução.

**Comment by juniorb2ss** [comment]
> Na real já foi feito isso. Ainda temos que investigar mais a fundo a real solução.

Foi corrigido o encoding dos arquivos, mas não o conteúdo, infelizmente há vários ainda como esse por exemplo:

https://github.com/oconfronto/oconfronto/blob/ff15b4a9c30e8ff8a96e13166739f4f37c3d55d1/src/monster.php#L768
