### ISSUE TITLE
[BUG] Forum

### ISSUE THREAD

**Issue by CassianoD2** [oconfronto/oconfronto#24]
Ao tentar acessar o fórum é retornado o erro:

![image](https://github.com/user-attachments/assets/6de4efba-d0a6-4248-8f78-0365a59f6f15)

Link acessado:
https://oc.jmr.technology/main_forum.php?cat=sugestoes

**Comment by jeeanribeiro** [comment]
@Diguzz o que acha de removermos o fórum e usar o Discord no lugar? Acho que fica mais simples de gerenciar

**Comment by Diguzz** [comment]
@jeeanribeiro concordo plenamente. Podemos descontinuar o fórum e implementar o discord para interatividade dos jogadores!
