### ISSUE TITLE
[BUG] Calculo/Validação de Pontos/STATUS

### ISSUE THREAD

**Issue by Kagijin** [oconfronto/oconfronto#25]
![image](https://github.com/user-attachments/assets/275a3938-ae37-4c3c-91e4-4055c3dc2582)

os status não funcionam de acordo.

**Comment by Diguzz** [comment]
@Kagijin Meu amigo, você adicionou esses pontos diretamente na coluna de vitalidade no banco de dados? Ou Adicionou em pontos de status e fez a distribuição dos pontos?

- Caso tenha adicionado esse valor diretamente na coluna `vitalidade ` da tabela `players`, ele não tem como base esse atributo para fazer o calculo da vida do player.
- Na realidade ele faz o calculo ( gerando o acrescimo a vida do player ) no momento em que o ponto é distribuido, conforme lógica do jogo quando se ganha um os pontos de status.

Sendo assim, não acredito que seja um bug.

**Comment by Kagijin** [comment]
Tem razão, desculpe pelo equivoco.
